# settings.yml
# Use this to define changeable values such as max_power.
# All values are in metric
# Unit of length is millimeters, not meters
# Unit of rotation is degrees (angular velocity is in degrees per second)

# Encoder pulses per full revolution http://ftcforum.usfirst.org/archive/index.php/t-5189.html
# update https://www.reddit.com/r/FTC/comments/3qhfvj/help_with_encoders/

# flags
alliance: red
position: general

encoder:
  output_pulses: 1440
  encoder_pulses: 28

# The drivetrain's settings.
drivetrain:
  motor_max_power: 1
  gear_ratio: 2.5
  motion:
    max_velocity: 100 # mm/s
    max_acceleration: 100 # mm2/s
    max_jerk: 100 # mm3/s
  motor:
    front_left:
      map_name: drive_front_left
      reversed: true
    front_right:
      map_name: drive_front_right
      reversed: false
    back_right:
      map_name: drive_back_left
      reversed: false
    back_left:
      map_name: drive_back_right
      reversed: false
  wheel:
    diameter: 101.6 # 4 inches

autonomous:
  red_alliance:
    starting_pos:
      x: 10.0
      y: 10.0
      rot: 0.0
    #Compute later
    travel_to_beacon:
      - move 100
      - stop
    travel_to_park:
      - move 100
      - stop
    travel_to_low:
      near:
        - move 100
        - stop
      far:
        - move 100
        - stop
    travel_to_mid:
      near:
        - move 100
        - stop
      far:
        - move 100
        - stop

  blue_alliance:
    starting_pos:
      x: 10.0
      y: 20.0
      rot: 0.0
    #Compute later
    travel_to_beacon:
      - move 100
      - stop
    travel_to_park:
      - move 100
      - stop
    travel_to_low:
      near:
        - move 100
        - stop
      far:
        - move 100
        - stop
    travel_to_mid:
      near:
        - move 100
        - stop
      far:
        - move 100
        - stop

  # This is the autonomous commands!
  command_list:
    - move 500
    - travel_to_beacon
    - drop_off_people
    - move -1000
    - climb_mountain_low near
    - stop

  # The below define the other commands that aren't alliance specific (make up your own if you want)
  drop_off_people:
    - winch_servo 50
    - winch_motor out,2
    - winch_servo down,5
    - winch_motor in,1


