# Component Configuration File

# Future Goals
#dc_motors:
#  dc_motor1:
#    enabled: true
#    extern_name: drive_left
#    intern_name: driveLeft


# Motors
dc_motors:
  dc_motor1:
    enabled: true
    map_name: drive_front_left
    alias:
      - driveFrontLeft
  dc_motor2:
    enabled: true
    map_name: drive_front_right
    alias:
      - driveFrontRight
  dc_motor3:
    enabled: true
    map_name: drive_back_right
    alias:
      - driveBackRight
  dc_motor4:
    enabled: true
    map_name: drive_back_left
    alias:
      - driveBackLeft
  dc_motor5:
    enabled: true
    map_name: intake
  dc_motor6:
    enabled: false #enable to true after installing motor
    map_name: flywheel

# Servos
servos:
  servo1:
    enabled: true
    map_name: bumper_left
    alias:
      - bumperLeft
  servo2:
    enabled: true
    map_name: bumper_right
    alias:
      - bumperRight

# Touch Sensors
touch_sensors:
  touch_sensor1:
    enabled: false
    map_name: touch_sensor
    alias:
      - button

# Light Sensors
light_sensors:
  light_sensor1:
    enabled: false #enable to true first
    map_name: light_sensor
    alias:
      - mod_rob_light_sensor
      - ods

# Color Sensors
color_sensors:
  color_sensor1:
    enabled: true
    map_name: color_sensor_left
    alias:
      - colorSensorLeft
  color_sensor2:
    enabled: true
    map_name: color_sensor_right
    alias:
      - colorSensorRight

# IR Seeker Sensors
ir_seekers:
  ir_seeker1:
    enabled: false
    map_name: main_ir_seeker
    alias:
      - ir_seeker1
      - ir1


# Gyrometers
gyrometers:
  gyrometer1:
    enabled: false
    using_phone: true
    # map_name: main_gyrometer
    alias:
      - gyrometer1
      - phone_gyro

# Accelermoters
accelerometers:
  accelerometer1:
    enabled: false
    using_phone: true
    # map_name: main_accelerometer

# Other components (whatever data structure - has to be initiated manually)
other:
  rangefinder:
    rangefinder1:
      analog_map_name: left_rangefinder_data
      digital_map_name: laft_rangefinder_toggle

# Camera

#TRASH

# Valid function types:
# color_grid    =     a grid of colors returned from the camera. Extra parameters are grid_x,
#                     grid_y, grid_side, and refresh_rate. grid_x and grid_y set the grid width
#                     & height; grid_side overrides grid_x and grid_y to set both width & height;
#                     refresh_rate sets how many times per second the grid is going to update itself.
#                     Either grid_x and grid_y or grid_size required. refresh_rate required. Will
#                     silently fail to load otherwise.
#
# NOTE: If function is undefined, it will silently assume that the device is disabled.
camera:
  camera1:
    enabled: false
    function: color_grid
    extra:
      grid_x: 3
      grid_y: 3
      grid_side: 3
      refresh_rate: 30.0
    alias:
      - color_grid
