# settings.yml
# Use this to define changeable values such as max_power.
# All values are in metric
# Unit of length is millimeters, not meters
# Unit of rotation is degrees (angular velocity is in degrees per second)

# Encoder pulses per full revolution http://ftcforum.usfirst.org/archive/index.php/t-5189.html
# update https://www.reddit.com/r/FTC/comments/3qhfvj/help_with_encoders/

# flags
alliance: red
position: general

catapult:
  map_name: catapult
  reversed: true
  light_sensor:
    map_name: ods
    threshold: .75
  power: .75
  position_tuning: 720
  tuning_power: .15
  forward_position: 1440
  grace: 500
  oscillation_max: .2
  power_increment: .001

#catapult:
#  light_tolerance: .75
#  target_position: 14400
#  ready_position: 1440
#  oscillation_max: 0.4
#  position_margin: 0
#  power_increment: 0.01
#  launch_power: 0.75
#  use_encoder: false
#  map_name: catapult
#  grace: 350

imu:
  map_name: imu

drop:
  full_rotate: 180.0
  offset: 0.0
  up_angle: 110.0
  down_angle: 0.0
  reversed: true
  map_name: drop
  
drive:
  diameter: 4.0
  gyro_margin: 3.0
  update_using: encoders
  init_using_fieldmap: false
  x_margin: 4.0
  y_margin: 4.0
  camera_settings:
    wait_time: 5000
    speed: 0.6
    centering_margin: 80.0
    distance_to_stop: 180.0
    angle_margin: 2.0
    beacon_check_distance: 100.0
    rotate_speed: 0.6
    rotate_factor: 1.6
  
auto:
  delay: 15000
  drive: 2750
  power: .81
  power_ratio: .778

lift:
  map_name: lift
  reversed: true

intake:
  divisor: 500
  map_name: intake
  reversed: false

robot:
  initial_position:
    x: 40
    y: -158.0
    initial_rotation: 0.0
    rot: 0.0
  size:
    x: 444.5    #width approx 17.5in
    y: 431.8    #length approx 15in
  imu_offset:
    x: 0.0
    y: 0.0
    z: 0.0
    r: 0.0
  phone_offset:
    x: 0.0
    y: 0.0
    z: 0.0
    r: 0.0

encoder:
  output_pulses: 1440
  encoder_pulses: 28
  centimeters_per_pulse: 0.0287

# The drivetrain's settings.
drivetrain:
  motor_max_power: 1
  motor_angle: 30
  gear_ratio: 2.5
  motor_scale: .778
  power: .778
  motion:
    max_velocity: 100 # mm/s
    max_acceleration: 100 # mm^2/s
    max_jerk: 100 # mm^3/s
  positional:
    rotation_min: 0.3
    rotational_tolerance: 1
    position_tolerance: 3.0
    speed: .778
    rotation: 0.6
  motor:
    front_left:
      map_name: drive_front_left
      reversed: true
    front_right:
      map_name: drive_front_right
      reversed: false
    back_right:
      map_name: drive_back_right
      reversed: true
    back_left:
      map_name: drive_back_left
      reversed: false
  wheel:
    diameter: 101.6 # 4 inches

# Front Bumper-thing Settings
bumper:
  enabled: true
  max_ang_vel: 80
  full_rotate: 180.0  #180 degree servo
  max_rotate: 60   #programmed limit
  preset: 45
  start_pos: 0.0
  left_servo:
    map_name: bumper_left
    reversed: true
    offset: 18
  right_servo:
    map_name: bumper_right
    reversed: false
    offset: 0

#color sensors
color_sensor:
  side: back
  left:
    map_name: color_sensor_left
    offset: 0.0
  right:
    map_name: color_sensor_right
    offset: 0.0

#Beacon colors
beacon:
  add_time: 250
  right_side_divisor: 3
  shift_time: 1300
  reverse_time: 2500
  press_time: 600
  check_time: 1000
  offset_time: 300
  max_check_time: 9000
  power: 0.6
  shift_power: 0.3
  press_power: 0.4
  fast_power: 0.6
  red:
    min: 300      #lower range of values
    max: 400       #upper range of values
  blue:
    min: 200
    max: 300
  value_min: 0
  saturation_min: 0.0

scriptauto:
  rotate:
    angle_margin: 1
    rotate_speed: .8
    min_speed: 0.2

autonomous:
  # This is the autonomous commands!
  command_list:
    - blue
    - stop
  blue:
    - pause 1000
    - catapult
    - move 100.0,-30.48
    - rotate 90,false
    - approach_beacon
    - claim_beacon
    - move_time .5,1000
    - rotate 0
    - move_time .5,5000
    - stop
    
  red:
    - pause 10000
    - move -20,-150
    - move -20,-158
    - catapult
    - pause 1000
    - catapult
    - move -100.0,-95.0
    - rotate 315,false
    - move_time .5,4000
    - stop
  drive:
    - coordinate 61.4,0.0
    - coordinate 0.0,61.4
    - coordinate 0.0,0.0
    - stop
  approach_beacon:
    - detect_image tools
    - center_rotate_image
    - approach_image
    - center_image

  # The below define the other commands that aren't alliance specific (make up your own if you want)
  test:
    - pause 1000
    - rotate 15
    - pause 1000
    - rotate 30
    - pause 1000
    - rotate 45
    - pause 1000
    - rotate 60
    - pause 1000
    - rotate 75
    - pause 1000
    - rotate 90,true
    - pause 1000
    - rotate 105,true
    - pause 1000
    - rotate 120
    - pause 1000
    - rotate 135
    - pause 1000
    - rotate 150
    - pause 1000
    - rotate 165
    - pause 1000
    - rotate 180
    - test


